add missing override specifiers
Building with clang fails with this representative message

  host_exerciser_lpbk.h:45:23: error: 'name' overrides a member
  function but is not marked 'override'
    virtual const char *name() const

Add the overrides.

Signed-off-by: Tom Rix <trix@redhat.com>