silence warning on may uninitialized variable first_sw_desc
On fedora rawhide with gcc 13, there is this error
opae-sdk/binaries/fpgabist/dma/fpga_dma.cpp: In function ‘void* dispatcherWorker(void*)’:
opae-sdk/binaries/fpgabist/dma/fpga_dma.cpp:507:48: error: ‘first_sw_desc’ may be used uninitialized [-Werror=maybe-uninitialized]
  507 |                                 first_sw_desc->hw_descp->hw_desc->owned_by_hw = 1;
      |                                 ~~~~~~~~~~~~~~~^~~~~~~~
opae-sdk/binaries/fpgabist/dma/fpga_dma.cpp:440:27: note: ‘first_sw_desc’ was declared here
  440 |         msgdma_sw_desc_t *first_sw_desc;
      |                           ^~~~~~~~~~~~~

Simplify the flow so the compiler does not get confused.

Signed-off-by: Tom Rix <trix@redhat.com>