rpm: add python3-pyyaml to list of requires
Fixes the build problem
  File ".../opae-libs/scripts/ofs/ofs_parse.py", line 35, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Signed-off-by: Tom Rix <trix@redhat.com>