qpafilter: adding QPA filter (#1939)
* doc: pin pygments,urllib3 to 2.7.4,1.26.3

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Squashed 'opae-libs/' changes from 385e9708..2bd1f299

2bd1f299 Merge pull request #141 from OPAE/aravuri/pyopaeuio
5428df44 opae-libs: fix code review comments
d0f4bd21 opae-libs: add python bindings for opaeuio module

git-subtree-dir: opae-libs
git-subtree-split: 2bd1f299fd751bb84f0b2b302ae019310228e8f9

* Update opae-libs

* qpafilter: adding QPA filter

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

* doc: pin urllib3 to 1.26.4

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Add logging module.

* Comprehend units in DATA_ITEM_PATTERN.

* qpafilter: new command options and cleanup.

Add command options -c,--crit-temp and -w,--warn-temp.
Change the list of tuples to a list of dictionaries with
keys {'label', 'critical', 'warning', 'units'}.
Clean up logging messages.

Add the notion of a filter class for each category. The filter
class calculates the warning threshold, given the critical value,
-c and -w.

* Add temperature override capability.

* opae-samples: fix he loopback number of cache lines

Signed-off-by: anandaravuri <ananda.ravuri@intel.com>

* qpafilter: clean up param names, override handling

Change --crit-temp to --virt-fatal-temp.
Change --warn-temp to --virt-warn-temp.
Change override processing to avoid another nested loop.

* qpafilter: move to subparsers {create,dump}

Changes 'critical' key to 'fatal'.

* ci: change build-rpms to run on PRs (#1925)

* Add 'pull_request' to 'on'
* Add condition to installing/testing RPMS to exclude 'pull_request'

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Revert "ci: merge opae-libs" (#1947)

* PACSign: remove "print" subparser.. (#1950)

Also remove related optional args, and the call to the
reader module.

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

* Remove opae-libs for subtree replacement

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Squashed 'opae-libs/' content from commit 30194d4c

git-subtree-dir: opae-libs
git-subtree-split: 30194d4c8a5023e7935fe1db64e38a29a3039c52

* fix the fpgalpbk issue

Signed-off-by: Tianfei zhang <tianfei.zhang@intel.com>
Signed-off-by: Ananda Ravuri <ananda.ravuri@intel.com>

* Add default list to override option.

* Squashed 'opae-libs/' changes from 30194d4c..db56419a

db56419a fix formatting (#152)

git-subtree-dir: opae-libs
git-subtree-split: db56419ab92d2b586b36db54666364ff0fc7900d

* rsu: add sdm image type (#1945)

Add bmc keyword with an alias of bmcimg. Changing to bmc follows
suit with the other image types. Preserving bmcimg allows client
scripts to remain unchanged.

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

* Fix arg parser checking.

* Squashed 'opae-libs/' changes from db56419a..6a760894

6a760894 add .gitattributes to this repo (#153)

git-subtree-dir: opae-libs
git-subtree-split: 6a7608941929a0011eb7618691b8999a2e3891c2

* modify .gitattributes (#1956)

* modify .gitattributes

Add .py, .rst, and .md extensions to be treated as text.
Because of this, some files will change in this PR to normalize from
CRLF to LF.

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* normalizing .md files

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Update update-repo.yml

* Squashed 'opae-libs/' changes from 6a760894..3424b5dc

3424b5dc opae-libs: fix coding style (#154)

git-subtree-dir: opae-libs
git-subtree-split: 3424b5dccecf9d6d3d06b03c109aaec84df7db93

* PACSign: add image types SDM and SDM_DEVEL (#1955)

* PACSign: add image types SDM and SDM_DEVEL

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

* Squashed 'opae-libs/' changes from 3424b5dc..f7ccfda5

f7ccfda5 default BUILD_LIBOFS to ON (#155)

git-subtree-dir: opae-libs
git-subtree-split: f7ccfda5cb27d837be71ce1bf7c73158351d186f

* Clang (#1943)

* remove unused private memebers

When building with clang 13, there is this representive error

  eth_group.h:138:6: error: private field 'container' is not used

Several other members are also unused.
So remove them.

Signed-off-by: Tom Rix <trix@redhat.com>

* fix usage of std::initialize_list

Building with clang fails with this error

  afu_test.h:242:35: error: array backing local initializer list
  'sinks' will be destroyed at the end of the full-expression
  [-Werror,-Wdangling]
    spdlog::sinks_init_list sinks({console_sink, file_sink});
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~

sinks_init_list is really
using sinks_init_list = std::initializer_list<sink_ptr>;

Because 'sinks' is only used in the constructor of logger,
remove the use of the variable 'sinks' and call sinks_init_list()
as a parameter of the constructor.

Signed-off-by: Tom Rix <trix@redhat.com>

* add missing override specifiers

Building with clang fails with this representative message

  host_exerciser_lpbk.h:45:23: error: 'name' overrides a member
  function but is not marked 'override'
    virtual const char *name() const

Add the overrides.

Signed-off-by: Tom Rix <trix@redhat.com>

* remove dead store

clang static analysis reports this error.

mmlink_connection.cpp:118:2: warning: Value stored to 'i' is never read
        i = 0;
        ^   ~

i is initialized before use in the for-loop, so remove this line.

Signed-off-by: Tom Rix <trix@redhat.com>

Co-authored-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* ofs_cpeng: fix yml format to create .h (#1961)

functions list is not longer supported.
Switching to use only 'api' blob

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Squashed 'opae-libs/' changes from 3424b5dc..c4f61c0d

c4f61c0d Merge pull request #156 from OPAE/aravuri/pyopaeuio_format
045163f9 opae-libs: fix coding style
f7ccfda5 default BUILD_LIBOFS to ON (#155)

git-subtree-dir: opae-libs
git-subtree-split: c4f61c0df568918df8472fb22f4b28837111be7d

* CI: enable coding style checks for opae-libs (#1958)


Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

* opae.admin: update database.py.. (#1962)

to keep bitstream_info.py in sync with recent PACSign changes.

Signed-off-by: Tim Whisonant <tim.whisonant@intel.com>

* update ofs_cpeng umd interface (#1964)

* update ofs_cpeng umd interface

* Update register map
* Update api functions to use changed registers
* ofs_cpeng: update test to use new registers

Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>

* Fix review comment

Co-authored-by: Rodrigo Rojo <rodrigo.rojo@intel.com>
Co-authored-by: OPAE Bot <opae_robot@intel.com>
Co-authored-by: r-rojo <r-rojo@users.noreply.github.com>
Co-authored-by: anandaravuri <ananda.ravuri@intel.com>
Co-authored-by: Ananda Ravuri <33236856+anandaravuri@users.noreply.github.com>
Co-authored-by: trixirt <trix@redhat.com>