fpgadiag, libopaecxx: link the libraries whose symbols are used
opae-cxx-core uses the fpga* C API from opae-c, and opae-c++-nlb uses
intel::utils from opae-c++-utils, but neither links the providing
library. This is invisible with the default linker behaviour but breaks
builds that link shared libraries with -Wl,-z,defs / --no-undefined
(e.g. openSUSE):

  undefined reference to `fpgaErrStr'
  undefined reference to `intel::utils::wrapped_stream::~wrapped_stream()'

Add the missing link dependencies so the libraries are self-contained.

Signed-off-by: Martin Pluskal <martin@pluskal.org>