rpm: add python3-jsonschema to BuildRequires
Using the create script on fedora, there is a build error

.../opae-libs/scripts/ofs/ofs_parse.py", line 33, in <module>
    import jsonschema
ModuleNotFoundError: No module named 'jsonschema'

So add python3-jsonschema to the requires list.

It was noted that python3-pip was listed twice in the create
script.  Remove one of them and reorder the list alphabetically.

Signed-off-by: Tom Rix <trix@redhat.com>