Add fmt to libraries to link with
On RHEL 8.2, there is this repesentative build error

/usr/bin/ld: CMakeFiles/hssi.dir/hssi.cpp.o: undefined reference to symbol '_ZTVN3fmt2v612format_errorE'
//usr/lib64/libfmt.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

So add the libfmt to the libraries to link with.

Signed-off-by: Tom Rix <trix@redhat.com>