tools: fix hssitools clang issues
1) Not used [-Werror,-Wunused-private-field]

opae-sdk/tools/extra/integrated/hssi/eth_ctrl.h:79:14: error: private field 'scratch_' is not used [-Werror,-Wunused-private-field]
    uint32_t scratch_;
             ^
opae-sdk/tools/extra/integrated/hssi/eth_ctrl.h:80:14: error: private field 'eth_arst_' is not used [-Werror,-Wunused-private-field]
    uint32_t eth_arst_;

2) [-Werror,-Winconsistent-missing-override]
opae-sdk/tools/extra/integrated/hssi/loopback.h:108:40: error: 'get_options' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
    virtual intel::utils::option_map & get_options()
    virtual void clear_status();
    virtual const std::string & afu_id() = 0;
   virtual void internal_loopback(uint32_t port);
   virtual bool setup();
 virtual bool run();

3)[-Werror,-Winconsistent-missing-override]
opae-sdk/tools/extra/integrated/hssi/e10.h:113:18: error: 'assign' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
 virtual void assign(opae::fpga::types::handle::ptr_t accelerator_ptr);

    virtual intel::utils::option_map & get_options()
    virtual void clear_status();
    virtual void internal_loopback(uint32_t port);
    virtual void external_loopback(uint32_t source_port, uint32_t destination_port);
    virtual void external_loopback(uint32_t source, uint32_t destination);
    virtual void stop(uint32_t instance, packet_flow flow);

4)[-Werror,-Winconsistent-missing-override]
opae-sdk/tools/extra/integrated/hssi/e40.h:113:18: error: 'assign' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
 virtual void assign(opae::fpga::types::handle::ptr_t accelerator_ptr);

    virtual intel::utils::option_map & get_options()
    virtual void clear_status();
    virtual void internal_loopback(uint32_t port);
    virtual void external_loopback(uint32_t source_port, uint32_t destination_port);
    virtual void external_loopback(uint32_t source, uint32_t destination);
    virtual void stop(uint32_t instance, packet_flow flow);
    virtual mac_report gen_report(uint32_t instance);
   virtual mac_report gen_report(uint32_t instace);# Please enter the commit message for your changes. Lines starting