remove unused private memebers
When building with clang 13, there is this representive error

  eth_group.h:138:6: error: private field 'container' is not used

Several other members are also unused.
So remove them.

Signed-off-by: Tom Rix <trix@redhat.com>