Improve initialization of pointer array object_paths. (#1437)
While '\0' will reduce to 0, the type of '\0' is char.
The base type of object_paths is not char, but rather char *
So use NULL which is usually defined as ((void *)0)

Fixes the clang compiler error

.../opae-sdk/libopae/plugins/xfpga/sysfs.c:2270:45: error: expression which evaluates to zero treated as a null pointer constant of type 'char *' [-Werror,-Wnon-literal-null-conversion]
        char *object_paths[MAX_SYSOBJECT_GLOB] = { '\0' };
                                                   ^~~~

Co-authored-by: Ananda Ravuri <33236856+anandaravuri@users.noreply.github.com>