fpgainfo: remove unused parameter in upcase_pci()
Clang 13 reports this error
fpgainfo.c:195:35: error: parameter 'len' set but not
  used [-Werror,-Wunused-but-set-parameter]
void upcase_pci(char *str, size_t len)
                                  ^
From inspection, the len parameter is never used.
So remove it.

Signed-off-by: Tom Rix <trix@redhat.com>