Trix/master/sa opae int
* Reorder includes so adapter.h is included before opae_int.h

opae_int.h uses struct _opae_api_adapter_table
struct _opae_api_adapter_table is defined in adapter.h

* Do not typedef opae_api_adapter_table in opae_int.h if adapter.h is included first

adapter.h has the primary definition of _opae_api_adapter_table
so typedef-ing it a second time is redundant.

Fixes the clang compiler error

.../opae-sdk/libopae/opae_int.h:96:40: error: redefinition of typedef 'opae_api_adapter_table' is a C11 feature [-Werror,-Wtypedef-redefinition]
typedef struct _opae_api_adapter_table opae_api_adapter_table;
                                       ^
.../opae-sdk/libopae/adapter.h:224:3: note: previous definition is here
} opae_api_adapter_table;

Co-authored-by: Ananda Ravuri <33236856+anandaravuri@users.noreply.github.com>