Remove use of CSR_AFU_DSM_BASEH
From inspection, this variable/#define is not used.
Instead CSR_AFU_DSM_BASEL is used in forms similar to

fpgaWriteMMIO64(accelerator_handle, 0, CSR_AFU_DSM_BASEL, iova);

Because a 64 bit write is always used, the high 32 bit of
CSR_AFU_DSM_BASE will never be used so CSR_AFU_DSM_BASEH can
be removed.

This is fixes a compile error with clang

.../opae-sdk/libopaecxx/samples/hello_fpga-1.cpp:60:23: error: unused variable 'CSR_AFU_DSM_BASEH' [-Werror,-Wunused-const-variable]
static const uint64_t CSR_AFU_DSM_BASEH = 0x0114;