Fix call to hwloc_set_membind_nodeset
In hwloc v1.11 the api for hwloc_set_membind_nodeset is

HWLOC_DECLSPEC int hwloc_set_membind_nodeset(hwloc_topology_t topology,
                                             hwloc_const_nodeset_t nodeset,
                                             hwloc_membind_policy_t policy,
                                             int flags);

The third parameter has a type of hwloc_membind_policy_t, however
HWLOC_MEMBIND_THREAD is of type hwloc_membind_flags_t.
This mismatch causes a compile error on the latest gcc

.../opae-sdk/tools/extra/pac/fpgabist/dma_vc/fpga_dma_test.c:730:30: error: implicit conversion from ‘enum <anonymous>’ to ‘hwloc_membind_policy_t’ [-Werror=enum-conversion]
  730 |     topology, obj2->nodeset, HWLOC_MEMBIND_THREAD,
      |                              ^~~~~~~~~~~~~~~~~~~~

Fix by replicating the calling of hwloc_set_membind_nodeset as is done in
fpga_dma_test_utils.cpp