Include <array> to get declaration of std::array type
The guid_t class' element 'data_' has std::array template type.
So it is necessary to include <array> to get the declaration of the type.

Fixes the clang + libc++ error

.../opae-sdk/common/include/opae/cxx/core/pvalue.h:133:27: error: implicit instantiation of undefined template 'std::__1::array<unsigned char, 16>'
  std::array<uint8_t, 16> data_;
                          ^
.../include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^