fix usage of std::initialize_list
Building with clang fails with this error

  afu_test.h:242:35: error: array backing local initializer list
  'sinks' will be destroyed at the end of the full-expression
  [-Werror,-Wdangling]
    spdlog::sinks_init_list sinks({console_sink, file_sink});
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~

sinks_init_list is really
using sinks_init_list = std::initializer_list<sink_ptr>;

Because 'sinks' is only used in the constructor of logger,
remove the use of the variable 'sinks' and call sinks_init_list()
as a parameter of the constructor.

Signed-off-by: Tom Rix <trix@redhat.com>